---
title: "Replication Examples Using Code"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Replication Examples Using Code}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  fig.width = 8,
  fig.height = 6,
  dpi = 150
)
```

```{r setup}
library(replicateEverything)

```


## System Architecture
This is the system architecture on which this package is built. There is a registry that host all the repositories for past studies. Then, the `replicateEverything` package interact with the repositories and then works the magic.
```{r, fig_1_example, echo=FALSE, fig.width=6, fig.height=4, out.width="70%", fig.align="center"}

suppressPackageStartupMessages(
  library(DiagrammeR)
)

DiagrammeR::grViz("
digraph {
  Registry -> 'Replication Repositories'
  'Replication Repositories' -> replicateEverything
}
")

```

# Run single replication 
```{r}
run_replication(
  "10.1177/00491241211036161",
  "fig_1"
)
```

# Replicate an entire paper 
```{r}
replicate_paper("10.1177/00491241211036161")
```
