#' Build registry index row for a folder-backed study
#' @keywords internal
folder_registry_index_row <- function(meta, study_root) {
  paper <- meta$paper
  authors <- paper$authors %||% ""
  if (length(authors) > 1) {
    authors <- paste(authors, collapse = ", ")
  } else {
    authors <- as.character(authors[[1]] %||% "")
  }
  data.frame(
    folder = doi_to_registry_folder(paper$doi),
    doi = normalize_doi(paper$doi),
    title = as.character(paper$title[[1]]),
    journal = as.character(paper$journal %||% ""),
    year = as.integer(paper$year %||% NA_integer_),
    authors = authors,
    repo = infer_study_repo_slug(study_root, meta),
    stringsAsFactors = FALSE
  )
}

#' Write registry stub files into a study repository
#'
#' Creates `registry/replication.yml` and `registry/index.csv` (one row) under the
#' study repo. After [check_folder_replication()] passes, copy these into the
#' [registry repository](https://github.com/replicate-anything/registry):
#'
#' - `registry/replication.yml` -> `papers/<folder>.yml`
#' - merge `registry/index.csv` into `index.csv`
#'
#' @param location Study repo path. Defaults to `"."`.
#' @param stub_dir Subdirectory under the study root; default `"registry"`.
#' @return List with `stub_dir`, `stub_path`, `index_path`, and `folder`.
#' @export
write_folder_registry_stub <- function(location = ".", stub_dir = NULL) {
  study_root <- resolve_study_location(location)
  meta <- read_study_replication_yaml(study_root)
  if (is.null(meta)) {
    stop("Missing replication.yml in ", study_root, call. = FALSE)
  }

  if (is.null(stub_dir) || !nzchar(stub_dir)) {
    stub_dir <- file.path(study_root, "registry")
  } else if (!dir.exists(stub_dir) && !grepl("^[A-Za-z]:[/\\\\]|^/", stub_dir)) {
    stub_dir <- file.path(study_root, stub_dir)
  }
  dir.create(stub_dir, recursive = TRUE, showWarnings = FALSE)

  study_folder <- basename(study_root)
  stub <- registry_stub_from_folder_meta(
    meta,
    study_folder = study_folder,
    study_root = study_root
  )
  folder <- doi_to_registry_folder(meta$paper$doi)

  stub_path <- file.path(stub_dir, "replication.yml")
  stub_yaml <- yaml::as.yaml(stub)
  header <- c(
    "# Lightweight registry stub for a folder-backed study.",
    "# Copy to registry/papers/<folder>.yml in the registry repo.",
    paste0("# Registry folder: ", folder),
    ""
  )
  writeLines(c(header, stub_yaml), stub_path, useBytes = TRUE)

  index_path <- file.path(stub_dir, "index.csv")
  utils::write.csv(folder_registry_index_row(meta, study_root), index_path, row.names = FALSE)

  readme_path <- file.path(stub_dir, "README.md")
  if (!file.exists(readme_path)) {
    writeLines(
      c(
        "# Registry sync files",
        "",
        "Generated by `replicateEverything::prepare_folder_paper()`.",
        "",
        paste0("- Copy `replication.yml` to `registry/papers/", folder, ".yml`"),
        "- Merge `index.csv` into the registry repo `index.csv` (replace any existing row with the same DOI).",
        "",
        "Or run `replicateEverything::sync_folder_paper()` with `registry_root` pointing at your registry checkout."
      ),
      readme_path
    )
  }

  invisible(list(
    stub_dir = stub_dir,
    stub_path = stub_path,
    index_path = index_path,
    folder = folder
  ))
}

#' Prepare a folder-backed study for registry sync
#'
#' Runs [build_study_artifacts()], [check_folder_replication()], and on success
#' writes `registry/replication.yml` and `registry/index.csv` in the study
#' repository. The only registry step left is syncing those files (see
#' [sync_folder_paper()]).
#'
#' @param location Study repo path. Defaults to `"."`.
#' @param build_artifacts If `TRUE`, run [build_study_artifacts()] first.
#' @param install_deps Passed to [build_study_artifacts()].
#' @param full_replication Passed to [check_folder_replication()].
#' @param registry_root Optional registry checkout for monorepo dev.
#' @return Invisibly, the result of [check_folder_replication()] with
#'   `registry_stub_path` and `registry_index_path` when successful.
#'
#' @examples
#' \dontrun{
#' prepare_folder_paper(".", registry_root = "../registry")
#' }
#'
#' @export
prepare_folder_paper <- function(
  location = ".",
  build_artifacts = TRUE,
  install_deps = TRUE,
  full_replication = FALSE,
  registry_root = NULL
) {
  if (isTRUE(build_artifacts)) {
    build_study_artifacts(
      location = location,
      install_deps = install_deps,
      registry_root = registry_root
    )
  }

  result <- check_folder_replication(
    location = location,
    full_replication = full_replication,
    registry_root = registry_root
  )

  if (!isTRUE(result$ok)) {
    message("Folder study validation failed:")
    failed <- result$checks[!result$checks$passed, , drop = FALSE]
    for (i in seq_len(nrow(failed))) {
      message("  [FAIL] ", failed$check[i], ": ", failed$message[i])
    }
    message(
      "\nSee vignette('folder-replication-checklist', package = 'replicateEverything') ",
      "for requirements."
    )
    return(invisible(result))
  }

  written <- write_folder_registry_stub(location)
  message(
    "All checks passed (", nrow(result$checks), " items). ",
    "Registry stub written under ", written$stub_dir
  )
  message("Sync to the registry with sync_folder_paper() or copy the files manually.")

  result$registry_stub_path <- written$stub_path
  result$registry_index_path <- written$index_path
  result$folder <- written$folder
  invisible(structure(result, class = c("folder_replication_check", "replication_check", "list")))
}

#' Copy prepared registry files into the registry repository
#'
#' Reads `registry/replication.yml` and `registry/index.csv` from the study
#' repo (written by [prepare_folder_paper()]) and installs them in a local
#' registry checkout.
#'
#' @param location Study repo path. Defaults to `"."`.
#' @param registry_root Path to the registry repository root. Defaults to
#'   `getOption("replicateEverything.registry_root")`.
#' @return Invisibly, a list with `stub_path`, `index_updated`, and `folder`.
#'
#' @examples
#' \dontrun{
#' options(replicateEverything.registry_root = "../registry")
#' sync_folder_paper(".")
#' }
#'
#' @export
sync_folder_paper <- function(location = ".", registry_root = NULL) {
  study_root <- resolve_study_location(location)
  local_stub <- file.path(study_root, "registry", "replication.yml")
  local_index <- file.path(study_root, "registry", "index.csv")

  if (!file.exists(local_stub)) {
    stop(
      "No registry/replication.yml in study repo. ",
      "Run prepare_folder_paper() first.",
      call. = FALSE
    )
  }
  if (!file.exists(local_index)) {
    stop(
      "No registry/index.csv in study repo. ",
      "Run prepare_folder_paper() first.",
      call. = FALSE
    )
  }

  if (is.null(registry_root) || !nzchar(registry_root)) {
    registry_root <- getOption("replicateEverything.registry_root", NULL)
  }
  if (is.null(registry_root) || !dir.exists(registry_root)) {
    stop(
      "registry_root not found. Pass the path to the registry repository or set ",
      "options(replicateEverything.registry_root = ...).",
      call. = FALSE
    )
  }

  row <- utils::read.csv(local_index, stringsAsFactors = FALSE)
  if (nrow(row) != 1L) {
    stop("registry/index.csv must contain exactly one row.", call. = FALSE)
  }
  folder <- row$folder[[1]]

  papers_dir <- file.path(registry_root, "papers")
  dir.create(papers_dir, recursive = TRUE, showWarnings = FALSE)
  stub_path <- file.path(papers_dir, paste0(folder, ".yml"))
  file.copy(local_stub, stub_path, overwrite = TRUE)
  legacy_dir <- file.path(papers_dir, folder)
  if (dir.exists(legacy_dir)) {
    unlink(legacy_dir, recursive = TRUE)
  }

  index_path <- file.path(registry_root, "index.csv")
  doi_norm <- normalize_doi(row$doi[[1]])
  if (file.exists(index_path)) {
    index <- utils::read.csv(index_path, stringsAsFactors = FALSE)
    index <- index[normalize_doi(index$doi) != doi_norm, , drop = FALSE]
    index <- rbind(index, row)
  } else {
    index <- row
  }
  utils::write.csv(index, index_path, row.names = FALSE)

  message("Synced registry stub: ", stub_path)
  message("Updated index: ", index_path)

  invisible(list(
    stub_path = stub_path,
    index_updated = index_path,
    folder = folder
  ))
}
